[package]
name = "labyrinth_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
itertools = "0.10.5"
rand = "0.8.5"
serde = {version = "1.0", optional = true}
