name: counter_dawn
description: A Dawn app
publish_to: none
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  dawn: ^6.0.2
dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers: ^3.2.7
  dawn_lints: ^3.0.0
