[package]
name = "labyrinth_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usvg = { workspace = true }
labyrinth_model = { path = "../labyrinth_model" }
